Add completion to quick_cd.

diff --git a/any/.config/zsh/aliases b/any/.config/zsh/aliases
--- a/any/.config/zsh/aliases
+++ b/any/.config/zsh/aliases
@@ -35,31 +35,38 @@ function docker-machine() {
 }
 
 function quick_cd() {
-. $(which set_cd_map.sh)
+  set_cd_map_sh=$(which set_cd_map.sh)
 
-if (( ! ${+CD_MAP} )); then
-  echo "CD_MAP not set!"
-  return 1
-fi
+  if [ $? -eq 1 ]; then
+    echo "set_cd_map.sh not found!"
+    return 1
+  fi
 
-if [[ $# -gt 1 || $# -eq 1 && (${argv[1]} == "-h" || ${argv[1]} == "--help") ]]; then
-  echo "Usage: quick_cd [directory abbreivation]"
-  return 1
-fi
+  . ${set_cd_map_sh}
 
-if [[ $# -eq 0 ]]; then
-  cd
-  return 1
-fi
+  if (( ! ${+CD_MAP} )); then
+    echo "CD_MAP not set!"
+    return 1
+  fi
 
-if (( ! ${+CD_MAP["$1"]} )); then
-  echo "No directory for $1"
-  return 1
-fi
+  if [[ $# -gt 1 || $# -eq 1 && (${argv[1]} == "-h" || ${argv[1]} == "--help") ]]; then
+    echo "Usage: quick_cd [directory abbreivation]"
+    return 1
+  fi
 
-echo "${CD_MAP[\"$1\"]}"
-cd "${CD_MAP[\"$1\"]}"
-return 0
+  if [[ $# -eq 0 ]]; then
+    cd
+    return 1
+  fi
+
+  if (( ! ${+CD_MAP[$1]} )); then
+    echo "No directory for $1"
+    return 1
+  fi
+
+  echo "${CD_MAP[$1]}"
+  cd "${CD_MAP[$1]}"
+  return 0
 }
 
 #aliases
